### ISSUE TITLE
[Study]Git Actions

### ISSUE THREAD

**Issue by saumonrose08** [nhnacademy-aiot2-javame/scrum_template#12]
<h1>🌐 GitHub Actions + Nginx 기반 정적 웹사이트 자동 배포 (CI/CD)</h1>
<hr>
<h2>🎯 최종 목표</h2>
<blockquote>
<p>index.html 파일을 GitHub에 push하면 자동으로 서버에 배포되고, 웹에서 실시간으로 확인할 수 있도록 한다.</p>
</blockquote>
<p>📍 최종 접속 주소 예시:</p>
<p><a href="http://s2.java21.net:10251/"><strong><a href="http://s2.java21.net:10251">http://s2.java21.net:10251</a></strong></a></p>
<hr>
<h2>🧱 전체 구성 요소 요약</h2>
<pre><code>[로컬 개발환경]
      │
      ▼ (git push)
[GitHub Repository]
      │
      ▼ (자동 실행)
[GitHub Actions (CI/CD)]
      │
      ▼ (SSH + SCP로 전송)
[원격 리눅스 서버]
      │
      ▼ (정적 파일 저장 위치)
/home/aiot2/aiot2-team3/frontend/index.html
      │
      ▼ (Nginx 서비스)
[외부 접근 가능 웹서버 - 포트 10251]

</code></pre>
<hr>
<h2>1️⃣ CI/CD란?</h2>

구분 | 용어 | 의미
-- | -- | --
CI | Continuous Integration | 코드 변경이 자동으로 병합/테스트됨
CD | Continuous Delivery / Deployment | 코드가 서버에 자동 배포/적용됨

# 🌐 GitHub Actions + Nginx 기반 정적 웹사이트 자동 배포 (CI/CD)

---

## 🎯 최종 목표

> index.html 파일을 GitHub에 push하면 자동으로 서버에 배포되고, 웹에서 실시간으로 확인할 수 있도록 한다.
> 

📍 최종 접속 주소 예시:

[**http://s2.java21.net:10251/**](http://s2.java21.net:10251/)

---

## 🧱 전체 구성 요소 요약

```
[로컬 개발환경]
      │
      ▼ (git push)
[GitHub Repository]
      │
      ▼ (자동 실행)
[GitHub Actions (CI/CD)]
      │
      ▼ (SSH + SCP로 전송)
[원격 리눅스 서버]
      │
      ▼ (정적 파일 저장 위치)
/home/aiot2/aiot2-team3/frontend/index.html
      │
      ▼ (Nginx 서비스)
[외부 접근 가능 웹서버 - 포트 10251]

```

---

## 1️⃣ CI/CD란?

| 구분 | 용어 | 의미 |
| --- | --- | --- |
| CI | Continuous Integration | 코드 변경이 자동으로 **병합/테스트**됨 |
| CD | Continuous Delivery / Deployment | 코드가 서버에 **자동 배포/적용**됨 |

### ✅ 왜 사용하는가?

| 상황 | 전통 방식 | CI/CD 방식 |
| --- | --- | --- |
| HTML 수정 후 배포 | 매번 수동으로 `scp` 또는 `ftp` | GitHub에 push만 하면 자동으로 배포됨 |
| 실수 발생 가능성 | 파일 누락, 오타 등 많음 | GitHub Actions가 자동 실행, 일관성 보장 |
| 팀 협업 시 | 누가 배포했는지 불명확 | 로그로 추적 가능, 공동 관리 쉬움 |

---

### 📁 경로: `.github/workflows/deploy.yml`

```yaml

name: Deploy Static HTML

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때만 실행됨

jobs:
  deploy-static-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # GitHub 코드 체크아웃

      - name: Upload via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "index.html"
          target: "/home/aiot2/aiot2-team3/frontend/"

```

### 🔐 GitHub Secrets 설정 필요

| 키 이름 | 설명 |
| --- | --- |
| `SSH_IP` | 서버 IP 주소 (`s2.java21.net`) |
| `SSH_ID` | 서버 접속 계정 (`aiot2-team3`) |
| `SSH_KEY` | 개인 키 (PEM 형식 내용) |
| `SSH_PORT` | 포트 번호 (`22`) |

→ `.pem` 파일은 `.gitignore`에 반드시 추가!

---

### 📁 디렉토리 구조 예시

```

/home/aiot2/aiot2-team3/
├── frontend/
   └── index.html   ← GitHub Actions가 자동으로 여기에 복사

```

---

### 🔧 설정 파일 예시: `/etc/nginx/sites-available/team3`

```

server {
    listen 10251;
    server_name s2.java21.net;

    location / {
        root /home/aiot2/aiot2-team3/frontend;
        index index.html;
    }
}

```

### 🛠 적용 절차

```bash

sudo ln -s /etc/nginx/sites-available/team3 /etc/nginx/sites-enabled/
sudo nginx -t                     # 설정 문법 검사
sudo systemctl reload nginx       # 설정 적용

```

---

## 5️⃣ 최종 동작 흐름 요약

```

[로컬 개발자가 index.html 수정]
        ▼
[git push origin main]
        ▼
[GitHub Actions가 자동 실행]
        ▼
[SCP로 서버에 파일 복사]
        ▼
[Nginx가 해당 포트(10251)로 서빙]
        ▼
[브라우저에서 http://s2.java21.net:10251로 접근]
        ▼
[index.html 최신 내용 확인]

```

---

## 6️⃣ 추가적으로 알면 좋은 것들

| 개념 | 설명 |
| --- | --- |
| 정적 웹사이트 | HTML/CSS/JS만으로 구성된 사이트 (서버 로직 없음) |
| SCP | Secure Copy. SSH 기반으로 서버에 파일 전송 |
| GitHub Actions | GitHub에서 제공하는 무료 CI/CD 도구 |
| Nginx | 고성능 웹서버. 정적 파일 서빙에 특화됨 |
| Secrets | GitHub에 보안 정보를 암호화해서 저장하는 공간 |
| `.gitignore` | 민감한 파일을 GitHub에 올리지 않도록 설정 |

---

## 🪄 팁: JS, CSS 함께 배포하려면?

```yaml
source: "."  # 현재 디렉토리 전체 업로드
target: "/home/aiot2/aiot2-team3/frontend/"
```

→ 폴더 구조:

```
css
복사편집
frontend/
├── index.html
├── style.css
├── main.js

```

→ Nginx 설정은 동일하게 유지 가능

---

## 🎁 정리

| 목표 | 사용 기술 | 설명 |
| --- | --- | --- |
| 코드 자동 배포 | GitHub Actions + SCP | main에 push → 서버에 자동 업로드 |
| 서버 접속 자동화 | SSH Key | 비밀번호 없이 안전한 접속 |
| 웹에서 확인 가능 | Nginx + 포트 개방 | 외부에서 직접 접속 가능 |
| 팀 충돌 방지 | 고유 포트 사용 (10251~10260) | 팀별 독립적 운영 가능 |
